# # vim:ft=ansible

unix_directories:
  - ~/.history

unix_packages:
  - autojump
  - btop
  - coreutils
  - curl
  - git
  - golang
  - htop
  - jq
  - nmap
  - python3-pip
  - python3
  - shellcheck
  - tree
  - vim
  - watch
  - wget
  - zsh

nerd_fonts:
  - "FiraMono"
  - "FiraCode"
  - "DaddyTimeMono"
  - "Go-Mono"

alpine:
  files:
    - { src: 'dotfiles/.vimrc', dest: '~/.vimrc' }
    - { src: 'dotfiles/.zshrc-linux', dest: '~/.zshrc' }
    - { src: 'dotfiles/.zshrc-common', dest: '~/.zshrc-common' }

darwin:
  files:
    - { src: 'dotfiles/.vimrc', dest: '~/.vimrc' }
    - { src: 'dotfiles/.bashrc', dest: '~/.bashrc' }
    - { src: 'dotfiles/.zshrc-mac', dest: '~/.zshrc' }
    - { src: 'dotfiles/.zshrc-common', dest: '~/.zshrc-common' }
    - { src: 'configs/ssh.config', dest: '~/.ssh/ssh.config' }
  casks:
    - arduino-ide
    - beekeeper-studio
    - blender
    - discord
    - docker
    - google-chrome
    - lens
    - logitech-g-hub
    - slack
    - spotify
    - steam
    - visual-studio-code
    - vlc
  packages:
    - awscli
    - balenaetcher
    - helm
    - iterm2
    - kubectl
    - kubectx

debian:
  xfce-configs: true
  files:
    - { src: 'dotfiles/.zshrc-common', dest: '~/.zshrc-common' }
    - { src: 'dotfiles/.zshrc-linux', dest: '~/.zshrc' }
    - { src: 'dotfiles/.Xmodmap', dest: '~/.Xmodmap' }
    - { src: 'dotfiles/.vimrc', dest: '~/.vimrc' }
  packages:
    - python3-winrm

windows:
  files:
    - {
      src: 'windows/MacToWinKeys.ahk',
      dest: '{{ lookup("env", "USERPROFILE") }}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\MacToWinKeys.ahk'}
    - {
      src: 'windows/Microsoft.PowerShell_profile.ps1',
      dest: '{{ lookup("env", "USERPROFILE") }}\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'}
    - {
      src: 'themes/oh-my-posh/kev.omp.json',
      dest: '{{ lookup("env", "USERPROFILE") }}\Documents\WindowsPowerShell\kev.omp.json'}
  packages:
    - git
