- name: Set Privilege Escalation Requirements
  ansible.builtin.set_fact:
    use_sudo: "{{ ansible_os_family != 'Darwin' }}"

- name: Install Unix Packages
  ansible.builtin.package:
    name: "{{ unix_packages }}"
    state: present
  become: "{{ use_sudo }}"
  become_flags: "-n"
  when: unix_packages is defined

- name: Install OS-Specific Packages (Mac/Linux)
  ansible.builtin.package:
    name: "{{ lookup('vars', ansible_os_family | lower).packages | default([]) }}"
    state: present
  become: "{{ use_sudo }}"
  when: lookup('vars', ansible_os_family | lower).packages is defined

- name: Include Darwin Tasks
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
