- name: Set privilege escalation variable
  ansible.builtin.set_fact:
    use_sudo: "{{ ansible_os_family != 'Darwin' and ansible_os_family != 'Windows' }}"

- name: Create Unix Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ unix_directories }}"
  when: ansible_os_family != 'Windows'

- name: Change the default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  when: ansible_os_family != 'Windows'

- name: Remove existing Oh My Zsh directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    state: absent
  when: ansible_os_family != 'Windows'

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: unset ZSH && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: ansible_os_family != 'Windows'

- name: Install Oh My Posh on Windows
  ansible.builtin.win_chocolatey:
    name: oh-my-posh
    state: present
  when: ansible_os_family == 'Windows'

- name: Ensure unzip is installed (Required for Oh My Posh)
  become: "{{ use_sudo }}"
  ansible.builtin.package:
    name: unzip
    state: present
  when: ansible_os_family != 'Windows'

- name: Download Oh My Posh install script
  ansible.builtin.get_url:
    url: https://ohmyposh.dev/install.sh
    dest: /tmp/install-oh-my-posh.sh
    mode: '0755'
  when: ansible_os_family != 'Windows'

- name: Install Oh My Posh Linux
  ansible.builtin.command:
    cmd: bash /tmp/install-oh-my-posh.sh
    creates: "{{ ansible_env.HOME }}/.poshthemes"
  when: ansible_os_family != 'Windows'

- name: Extract XFCE configs
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/../assets/configs/xfce-configs.tar.gz"
    dest: "/"
  when: ansible_os_family != 'Windows'
  tags: xfce

- name: Install Kali Win Kex
  become: true
  ansible.builtin.apt:
    name: kali-win-kex
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: ansible_distribution == 'Kali'
  tags: kex
