- name: Include Unix Tasks
  ansible.builtin.include_tasks: unix.yml
  when: ansible_distribution != 'Windows'

- name: Include Windows Tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_distribution == 'Windows'
