- name: Set privilege escalation variable
  ansible.builtin.set_fact:
    use_sudo: "{{ ansible_os_family != 'Darwin' and ansible_os_family != 'Windows' }}"

- name: Create Unix Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ unix_directories }}"
  when: ansible_os_family != 'Windows'

- name: Change the default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  when: ansible_os_family != 'Windows'

- name: Remove existing Oh My Zsh directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    state: absent
  when: ansible_os_family != 'Windows'

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: unset ZSH && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  when: ansible_os_family != 'Windows'

- name: Install Oh My Posh on Windows
  ansible.builtin.win_chocolatey:
    name: oh-my-posh
    state: present
  when: ansible_os_family == 'Windows'

- name: Ensure unzip is installed (Required for Oh My Posh)
  become: "{{ use_sudo }}"
  ansible.builtin.package:
    name: unzip
    state: present
  when: ansible_os_family != 'Windows'

- name: Download Oh My Posh Install Script
  ansible.builtin.get_url:
    url: https://ohmyposh.dev/install.sh
    dest: /tmp/install-oh-my-posh.sh
    mode: '0755'
  when: ansible_os_family != 'Windows'

- name: Install Oh My Posh (Mac/Linux)
  ansible.builtin.command:
    cmd: bash /tmp/install-oh-my-posh.sh
    creates: "{{ ansible_env.HOME }}/.poshthemes"
  when: ansible_os_family != 'Windows'

- name: Extract XFCE Configs
  become: true
  ansible.builtin.unarchive:
    src: "{{ playbook_dir }}/../assets/configs/xfce-configs.tar.gz"
    dest: "{{ ansible_env.HOME }}/.config"
    remote_src: true
  when:
    - ansible_distribution == 'Kali'
    - debian.xfce_configs is defined
    - debian.xfce_configs
  tags: xfce

- name: Change Ownership of XFCE Config Directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/xfce4"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    recurse: true
    state: directory
  when:
    - ansible_distribution == 'Kali'
    - debian.xfce_configs is defined
    - debian.xfce_configs
  tags: xfce

- name: Determine if Kali is Running in WSL
  ansible.builtin.command:
    cmd: grep -qEi "(Microsoft|WSL)" /proc/version && echo true || echo false
  register: kali_wsl_check
  changed_when: false
  when: ansible_distribution == 'Kali'

- name: Set fact for Kali Win Kex
  ansible.builtin.set_fact:
    kali_wsl: "{{ kali_wsl_check.stdout | bool }}"
  when: ansible_distribution == 'Kali'

- name: Debug kali_wsl value
  ansible.builtin.debug:
    msg: "kali_wsl is {{ kali_wsl }}"
  when: ansible_distribution == 'Kali'

- name: Install Kali WSL Packages
  become: true
  ansible.builtin.apt:
    name: kali-win-kex
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items:
    - kali-win-kex
    - python3-winrm
  when: ansible_distribution == 'Kali' and kali_wsl
  tags: kex

- name: Change Default Shell - win-kex xstartup
  become: true
  ansible.builtin.replace:
    path: /usr/lib/win-kex/xstartup
    regexp: 'export SHELL=/bin/bash'
    replace: 'export SHELL=/bin/zsh'
  when: ansible_distribution == 'Kali' and kali_wsl
  tags: kex
