- name: Install Nerd Fonts (Linux)
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/{{ item }}.zip"
    dest: "/usr/local/share/fonts/"
    creates: "/usr/local/share/fonts/{{ item }}"
    remote_src: true
    keep_newer: true
    exclude: 
      - "*.md"
      - "LICENSE*"
  with_items: "{{ nerd_fonts }}"
  when: ansible_os_family not in ['Darwin', 'Windows']

- name: Install Nerd Fonts (Darwin)
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/{{ item }}.zip"
    dest: "/Library/Fonts/"
    creates: "/Library/Fonts/{{ item }}"
    remote_src: true
    keep_newer: true
    exclude: 
      - "*.md"
      - "LICENSE*"
  with_items: "{{ nerd_fonts }}"
  when: ansible_os_family == 'Darwin' 

- name: Install Nerd Fonts (Windows)
  ansible.builtin.win_unzip:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/{{ item }}.zip"
    dest: "C:\\Windows\\Fonts\\"
    creates: "C:\\Windows\\Fonts\\{{ item }}"
    remote_src: true
    keep_newer: true
  with_items: "{{ nerd_fonts }}"
  when: ansible_os_family == 'Windows'
