- name: Unix Tasks
  ansible.builtin.include_tasks: unix.yml
  when: ansible_os_family not in ['Darwin', 'Windows']

- name: Darwin Tasks
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Windows Tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
