- name: Provisions Local Machine
  hosts: local remote
  gather_facts: true
  roles:
    - { role: packages, tags: ['packages'] }
    - { role: system, tags: ['system'] }
    - { role: files, tags: ['files'] }
    - { role: nerd-fonts, tags: ['nerd-fonts'] }
    - { role: golang, tags: ['go'] }
